### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by EgorkillerUA** [joctopus/Yellow#18]
* В ВР не работают хоткеи. При попадании туда вырубается hotkey mode, пропадает кнопка в правом нижнем углу, нажатие кнопкии в панели команд ничего не дает. По возвращении из ВР хоткеи не возвращаются, лечится перезаходом.
* На распечатанных заметках из ПДА нельзя писать. При нажатии на write открыается окно ПДА.

**Comment by Alchemist120** [comment]
- Фаерлоки покрывают шлюзы, что мешает их закрытию без alt+click.
- НаноУИ не закрывающийся.
- Фоточки не грузятся в ПДА.
- Кривой ЦК с кривыми шлюзами.
- Музыкальные инструменты.
- Нужно ещё раз чекнуть кравл, по некоторым поверхностям, говорят, нельзя ползти.
